### ISSUE TITLE
Is Lumen supported?

### ISSUE THREAD

**Issue by jfoliveira** [mathiasgrimm/laravel-env-validator#6]
Hi, thanks for publishing this very useful package!

I know the package name says `Laravel` but as Laravel and Lumen are often used together I'm curious: 

is this package supposed to work with Lumen?

Tried it on a Lumen project and this exception is raised:

```
Fatal error: Call to undefined function MathiasGrimm\LaravelEnvValidator\config_path() in 
/vendor/mathiasgrimm/laravel-env-validator/src/ServiceProvider.php on line 16
```

It seems [many other packages had the same issue in the past](https://www.google.com.br/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=lumen+Call+to+undefined+function+config_path%28%29)

If Lumen is not aimed to be supported please let us know.

Thanks!

**Comment by mathiasgrimm** [comment]
I haven't tested it with Lumen.
The idea is that it should be supported, however, will run some tests and see how it goes.

Thanks for raising the issue

**Comment by jfoliveira** [comment]
One change you might want to make is on `src/EnvValidatorFactory.php`:

``` php
public static function buildFromLaravelConfig()
{
    // $config    = \Config::get('laravel-env-validator'); # doesn't work with Lumen
    $config    = config('laravel-env-validator'); # <<< this works with Lumen. Not sure if it works with Laravel
```

Also, I would suggest creating a separate `LumenServiceProvider` to make it easier for you to maintain the package having the providers completely independent.

**Comment by mathiasgrimm** [comment]
Good idea.

**Comment by jfoliveira** [comment]
In case you need references, I would suggest:
`laravel-cors`:
 https://github.com/barryvdh/laravel-cors/blob/master/src/LumenServiceProvider.php 

`jwt-auth`:
https://github.com/tymondesigns/jwt-auth/blob/develop/src/Providers/LumenServiceProvider.php

**Comment by mathiasgrimm** [comment]
Nice, will have a look on them!

Would you like to test yourself and submit a PR maybe? :)

**Comment by jfoliveira** [comment]
Ok, will do. Would you mind creating a `develop` branch to make it easier to use `git flow`?

**Comment by jfoliveira** [comment]
Please ignore my last comment about creating develop branch. I set up `git flow` on my fork and it's fine. Thanks!

**Comment by jfoliveira** [comment]
Done #7

**Comment by ghost** [comment]
+1 for Lumen support.
I've just downloaded and it's not working with Lumen. :-(
Is this package ready for using with Lumen now?

**Comment by mathiasgrimm** [comment]
Done!
